### ISSUE TITLE
Define and check UserQueueToken-reuse

### ISSUE THREAD

**Issue by benbender** [impfen/services-inoeg#15]
A user can generate multiple QueueTokens from the same secret. Those tokens will have the same booking-code, but seem to be technically working and valid. We have to define, implement and test the desired behaviour.

**Comment by tauli** [comment]
Ist das Ticket soweit geklärt? Umsetzung würde ich in #37 tracken.

**Comment by bkastl** [comment]
Ja, mit der Konfiguration wie in #37 beschrieben, geklärt.
